### ISSUE TITLE
Not working on Windows VSCode

### ISSUE THREAD

**Issue by rleyvasal** [quarto-dev/quarto-vscode#16]
VSCode giving error "Quarto Installation not found" when trying to render.

I am not sure if the following steps to install Quarto is correct because I did not find detail instructions on installation on [Quarto Get Started page](https://quarto.org/docs/get-started/)  

I followed the next sequence to install Quarto:
1. installed Quarto for [Windows](https://quarto.org/docs/get-started/)
2. installed Quarto VSCode extension from VSCode extensions menu (left side of screen)
3.  Created Quarto file and render giving error "Quarto Installation not found"

![installation errror](https://user-images.githubusercontent.com/61335136/166980721-4d8a2c4d-e16f-4763-b32f-599d468ef861.PNG)

Going to the settings of Quarto in VSCode  I changed the PATH to point to where Quarto `quarto.cmd` is located in my PC but still get the same error when trying to render the file. 

![path to cli](https://user-images.githubusercontent.com/61335136/166980761-5778d28c-68da-4d83-ae70-504f5f6696c1.PNG)

**Comment by jjallaire** [comment]
Sorry to hear that this is happening! It's possible that the Quarto installation didn't complete successfully? What happens if you type `quarto check` in Powershell? What about `quarto --version`

The VS code extension will search for Quarto on your PATH (although you may need to restart VS Code for it to actually show up on your PATH).

**Comment by rtockner1** [comment]
Since the last automatic update from VSCode I am receiving an error message when rendeing a quarto file within VSCode. 

![2022-05-06 16_09_18-Untitled-2 qmd - Visual Studio Code](https://user-images.githubusercontent.com/91114385/167150829-3463a714-494e-48f5-b1bb-07e2ad4efe5b.png)

Quarto Check ist ok: 

![2022-05-06 16_09_40-Untitled-2 qmd - Visual Studio Code](https://user-images.githubusercontent.com/91114385/167150941-b66f973b-6522-43d9-9432-2d441ccdbe53.png)

I am using quarto Version 0.9.351 
Quarto Extension: Version. 1.1.191

VSCode Version:
![2022-05-06 16_13_20-Erweiterung_ Quarto - Visual Studio Code](https://user-images.githubusercontent.com/91114385/167151250-248b87c1-b39e-4be7-a856-f26aceb3775f.png)

**Comment by rleyvasal** [comment]
It is working for me after I restarted by PC. Maybe a comment should be added Get Started guide inform users to reboot after installation.

**Comment by jjallaire** [comment]
Interesting. It's isn't generally required to restart your PC (but I do think that you might need to restart VS Code, I'll definitely add a note to that effect)
